# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Memorious
tagline:          "Don't read this blog."
description:      'My name is David Davis. This is my blog.'
url:              http://blog.memorious.net
baseurl:          '/'
paginate:         5
tags_path:        /tags/
categories_path:  /categories/
date_format:      "%B %e, %Y"
timezone:         "America/New_York"

author:
  name:           'David Davis'
  url:            http://memorious.net
  twitter:        davidtdavis
  gplus:          "https://plus.google.com/+DavidDavis42/posts"

# comments
disqus:
  enabled:        true
  short_name:     "memorious-net"

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://blog.memorious.net'
  media: 'public/img/posts'
  ignore:
    - README.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          label: "Title"
          element: "text"
      - name: "image"
        field:
          label: "Image"
          element: "text"
      - name: "description"
        field:
          label: "Description"
          element: "text"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          label: Category
          element: "select"
          options:
            - name: "Technology"
              value: "technology"
            - name: "Literature"
              value: "literature"
            - name: "Music"
              value: "music"
            - name: "Other"
              value: "other"
