# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Memorious
tagline:          "Don't Read this blog."
description:      'My name is David Davis. This is my blog.'
url:              http://blog.memorious.net
baseurl:          '/'
paginate:         5
tags_path:        /tags/

author:
  name:           'David Davis'
  url:            http://memorious.net
  twitter:        davidtdavis
  gplus:          http://plus.google.com/+DavidDavis42/posts
