# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Memorious
tagline:          "Don't read this blog."
description:      'My name is David Davis. This is my blog.'
url:              http://blog.memorious.net
baseurl:          '/'
paginate:         5
tags_path:        /tags/
categories_path:  /categories/

author:
  name:           'David Davis'
  url:            http://memorious.net
  twitter:        davidtdavis
  gplus:          http://plus.google.com/+DavidDavis42/posts

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://blog.memorious.net'
  media: 'public/img/posts/'
  ignore:
    - README.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "select"
          options:
            - name: "Technology"
              value: "technology"
            - name: "Literature"
              value: "literature"
            - name: "Music"
              value: "music"
            - name: "Other"
              value: "other"
