# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Memorious
tagline:          "Don't Read this blog."
description:      'My name is David. This is my blog. You can also follow <a href="//twitter.com/davidtdavis">@davidtdavis</a> on Twitter.'
url:              http://blog.memorious.net
baseurl:          '/'
paginate:         5

author:
  name:           'David Davis'
  url:            http://memorious.net
  twitter:        https://twitter.com/davidtdavis
